// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfrRIR-YbHRWWtFz4prR7NcRQi4Qyn6s',
    appId: '1:580000711382:web:cae4a03ec00dfb4246bf77',
    messagingSenderId: '580000711382',
    projectId: 'resume-task',
    authDomain: 'resume-task.firebaseapp.com',
    storageBucket: 'resume-task.appspot.com',
    measurementId: 'G-3DXSZ2RKDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuOG8c4NXBJS0e4dlICDCPpKj4mt-Yv0',
    appId: '1:580000711382:android:235002574093816746bf77',
    messagingSenderId: '580000711382',
    projectId: 'resume-task',
    storageBucket: 'resume-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNJbvVfuv3MEAbGJkLG5L2vl-ct70jK4',
    appId: '1:580000711382:ios:17a6a40aeecaf96346bf77',
    messagingSenderId: '580000711382',
    projectId: 'resume-task',
    storageBucket: 'resume-task.appspot.com',
    iosBundleId: 'com.example.resumeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRNJbvVfuv3MEAbGJkLG5L2vl-ct70jK4',
    appId: '1:580000711382:ios:e2ce359d5fa547a046bf77',
    messagingSenderId: '580000711382',
    projectId: 'resume-task',
    storageBucket: 'resume-task.appspot.com',
    iosBundleId: 'com.example.resumeTask.RunnerTests',
  );
}
